invoice_string = """LAWLER BALLARD VAN DURAND
2512 FLAGSTONE CIRCLE
BIRMINGHAM, ALABAMA 35226
INVOICE

ATTN: MIRANDA SMITH
COMPANY: THOMPSON TRACTOR COMPANY
ADDRESS: PO BOX 10367 BIRMINGHAM, AL 35202-0367

INVOICE NO. <<invoice>>
DATE: <<date>>
JOB: <<job>>
DESCRIPTION: <<description>>

TOTAL DUE: <<billing>>

THANK YOU"""
